const pages=[['Bonfire','index.html','<img class="nav-icon" src="assets/bonfire.png" alt="">'],['Character Sheet','whoami.html','<img class="nav-icon" src="assets/charecter.png" alt="">'],['Forge','projects.html','<img class="nav-icon" src="assets/forge.png" alt="">'],['Covenants','certifications.html','<img class="nav-icon" src="assets/COVENANTS.png" alt="">'],['Lore','blogs.html','<img class="nav-icon" src="assets/lore.png" alt="">'],['Linking the Fire','challenge.html','<img class="nav-icon" src="assets/link_fire.png" alt="">']];
const current=location.pathname.split('/').pop()||'index.html';
document.body.insertAdjacentHTML('afterbegin','<div class="bg-layer" aria-hidden="true"></div><div class="overlay" aria-hidden="true"></div>');
document.body.insertAdjacentHTML('afterbegin',`<canvas id="embers"></canvas><div class="transition"></div><header class="topbar"><a class="brand" href="index.html"><span><img src="assets/bonfire.png" alt="bonfire" style="width: 36px; height: 36px; object-fit: contain; vertical-align: middle;"></span>YOUR NAME</a><button class="hamb" aria-label="Open menu">☰</button><nav class="navlinks">${pages.map(([n,u,i])=>`<a class="${current===u?'active':''}" href="${u}">${i} ${n}</a>`).join('')}</nav></header><button class="sound" aria-label="Toggle bonfire ambience" title="Toggle bonfire ambience"><img src="assets/bonfire.png" alt="bonfire" style="width: 28px; height: 28px; object-fit: contain; vertical-align: middle;"></button>`);
document.body.insertAdjacentHTML('beforeend',`<footer class="footer"><div class="brand"><img src="assets/bonfire.png" alt="bonfire" style="width: 28px; height: 28px; object-fit: contain; vertical-align: middle;"> YOUR NAME · UNKINDLED OPERATIVE</div><div>“Seek strength. The rest will follow.”</div><div class="social"><a href="#">GitHub</a><a href="#">LinkedIn</a><a href="#">HTB</a></div><small>© 2026 · Forged in the First Flame</small></footer>`);
const nav=document.querySelector('.navlinks');document.querySelector('.hamb').onclick=()=>nav.classList.toggle('open');
document.querySelectorAll('a[href$=".html"]').forEach(a=>a.addEventListener('click',e=>{if(a.origin===location.origin&&a.pathname!==location.pathname){e.preventDefault();document.querySelector('.transition').classList.add('on');setTimeout(()=>location.href=a.href,400)}}));
// Ambient audio placeholder: replace the src below when a bonfire clip is supplied.
let audio=null;document.querySelector('.sound').onclick=()=>{if(!audio){audio=new Audio('assets/bonfire-audio-placeholder.mp3');audio.loop=true}if(audio.paused){audio.play().catch(()=>{});document.querySelector('.sound').style.textShadow='0 0 12px #f4a14a'}else{audio.pause();document.querySelector('.sound').style.textShadow='none'}};
const canvas=document.querySelector('#embers'),ctx=canvas.getContext('2d');let w,h,embers=[];function resize(){w=canvas.width=innerWidth;h=canvas.height=innerHeight;embers=Array.from({length:26},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*2+0.5,v:Math.random()*.45+.15,a:Math.random()*.6+.1}))}resize();addEventListener('resize',resize);function draw(){ctx.clearRect(0,0,w,h);for(const e of embers){e.y-=e.v;e.x+=Math.sin(e.y*.012)*.18;if(e.y<0){e.y=h;e.x=Math.random()*w}ctx.fillStyle=`rgba(244,161,74,${e.a})`;ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}draw();
document.querySelectorAll('.inspect').forEach(b=>b.onclick=()=>{const d=JSON.parse(b.dataset.detail||'{}');document.querySelector('#modal-title').textContent=d.title||'Item inspection';document.querySelector('#modal-content').innerHTML=d.body||'';document.querySelector('.modal').classList.add('show')});document.querySelectorAll('.modal-close').forEach(b=>b.onclick=()=>document.querySelector('.modal').classList.remove('show'));document.querySelector('.modal')?.addEventListener('click',e=>{if(e.target.classList.contains('modal'))e.currentTarget.classList.remove('show')});
document.querySelectorAll('.read-post').forEach(b=>b.onclick=()=>{const d=document.getElementById(b.dataset.target);d.classList.toggle('open');b.textContent=d.classList.contains('open')?'LEAVE INSCRIPTION':'READ INSCRIPTION';const msg=['Try jumping','Praise the sun!','Be wary of ahead','Keep moving forward'];d.querySelector('.soap span').textContent=msg[Math.floor(Math.random()*msg.length)]});
document.querySelectorAll('.attempt').forEach(b=>b.onclick=()=>{const r=b.parentElement.querySelector('.riddle');r.classList.toggle('open');b.textContent=r.classList.contains('open')?'CLOSE':'ATTEMPT CHALLENGE'});
document.querySelectorAll('.answer').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter'){const ok=i.value.trim().toLowerCase()===i.dataset.answer.toLowerCase();const card=i.closest('.boss');card.querySelector('.status').textContent=ok?'LINKED':'STILL SEALED';if(ok){card.classList.add('solved');i.disabled=true;updateProgress()}else i.value=''}}));function updateProgress(){const n=document.querySelectorAll('.boss.solved').length,total=document.querySelectorAll('.boss').length,p=Math.round(100*n/total);document.querySelector('.progressbar').style.setProperty('--progress',p+'%');document.querySelector('.soul-count').textContent=`SOULS COLLECTED: ${n} / ${total} CINDERS LINKED`;document.querySelector('.progress span').textContent=`${p}%`;if(n===total)document.querySelector('.firelink').classList.add('ready')};document.querySelector('.firelink')?.addEventListener('click',()=>{if(document.querySelectorAll('.boss.solved').length===4)document.querySelector('.final-flame').classList.add('show')});
